config/routes.rb
Wero::Application.routes.draw do
  devise_for :users

  get 'admin' => 'admin/index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "time_add/index"

  get "timeroster_line/index"

  resources :time_rosters
  
  root :to => "timeroster_line#index"
  
  match '(/:year(/:month))' => "timeroster_line#index", :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  devise_for :users

end

app/models/time_roster.rb
class TimeRoster < ActiveRecord::Base
  has_one :timeroster_line
  attr_accessible :going_work_time, :quit_work_time, :work_date
  
end

app/controllers/time_rosters_controller.rb
class TimeRostersController < ApplicationController
  # GET /time_rosters
  # GET /time_rosters.json
  def index
    @time_rosters = TimeRoster.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @time_rosters }
    end
  end

  # GET /time_rosters/1
  # GET /time_rosters/1.json
  def show
    @time_roster = TimeRoster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @time_roster }
    end
  end

  # GET /time_rosters/new
  # GET /time_rosters/new.json
  def new
    @time_roster = TimeRoster.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @time_roster }
    end
  end

  # GET /time_rosters/1/edit
  def edit
    @time_roster = TimeRoster.find(params[:id])
  end

  # POST /time_rosters
  # POST /time_rosters.json
  def create
    @form_data = params[:time_roster]
    @work_date = @form_data["work_date(1i)"] + "-" + @form_data["work_date(2i)"] + "-" + @form_data["work_date(3i)"]
    @going_work_time = @form_data["going_work_time"]
    @quit_work_time = @form_data["quit_work_time"]
    
    if TimeRoster.exists?(['work_date like ?', "%#{@work_date}%"])
      redirect_to :controller => "time_rosters", :action => "index" 
      @time_roster = TimeRoster.find(:all, :conditions => {:work_date => @work_date})
      if @time_roster.update_attributes({:going_work_time => @going_work_time, :quit_work_time => @quit_work_time})  
        redirect_to :controller => "time_rosters", :action => "index" 
      end
    else
      @time_roster = TimeRoster.new(params[:time_roster])
      if @time_roster.save
        @timeroster_line = @time_roster.build_timeroster_line
        @timeroster_line.user = current_user
        if @timeroster_line.save
          redirect_to :controller => "timeroster_line", :action => "index"
        end
      end
    end



  end

  # PUT /time_rosters/1
  # PUT /time_rosters/1.json
  def update
    @time_roster = TimeRoster.find(params[:time_roster])

    respond_to do |format|
      if @time_roster.update_attributes(params[:time_roster])
        format.html { redirect_to @time_roster, notice: 'Time roster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @time_roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_rosters/1
  # DELETE /time_rosters/1.json
  def destroy
    @time_roster = TimeRoster.find(params[:id])
    @time_roster.destroy

    respond_to do |format|
      format.html { redirect_to time_rosters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/time_rosters_helper.rb
module TimeRostersHelper
end

app/views/time_rosters/_form.html.erb
<%= form_for(@time_roster) do |f| %>
  <% if @time_roster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_roster.errors.count, "error") %> prohibited this time_roster from being saved:</h2>

      <ul>
      <% @time_roster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :work_date %><br />
    <%= f.date_select :work_date %>
  </div>
  <div class="field">
    <%= f.label :going_work_time %><br />
    <%= f.text_field :going_work_time , :value => "9:00", :size => 10 %>
  </div>
  <div class="field">
    <%= f.label :quit_work_time %><br />
    <%= f.text_field :quit_work_time , :value => Time.now.strftime("%H:%M") ,:size => 10 %>
		<input type="text" id="defaultEntry" size="10"></p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_rosters/edit.html.erb
<h1>Editing time_roster</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_roster %> |
<%= link_to 'Back', time_rosters_path %>

app/views/time_rosters/index.html.erb
<h1>Listing time_rosters</h1>

<table>
  <tr>
    <th>Work date</th>
    <th>Going work time</th>
    <th>Quit work time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @time_rosters.each do |time_roster| %>
  <tr>
    <td><%= time_roster.work_date %></td>
    <td><%= time_roster.going_work_time.strftime('%H:%M:%S').to_s %></td>
    <td><%= time_roster.quit_work_time.strftime('%H:%M:%S').to_s %></td>
    <td><%= time_roster.going_work_time %></td>
    <td><%= time_roster.quit_work_time %></td>
    <td><%= link_to 'Show', time_roster %></td>
    <td><%= link_to 'Edit', edit_time_roster_path(time_roster) %></td>
    <td><%= link_to 'Destroy', time_roster, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Time roster', new_time_roster_path %>

app/views/time_rosters/new.html.erb
<h1>New time_roster</h1>

<%= render 'form' %>

<%= link_to 'Back', time_rosters_path %>

app/views/time_rosters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Work date:</b>
  <%= @time_roster.work_date %>
</p>

<p>
  <b>Going work time:</b>
  <%= @time_roster.going_work_time %>
</p>

<p>
  <b>Quit work time:</b>
  <%= @time_roster.quit_work_time %>
</p>


<%= link_to 'Edit', edit_time_roster_path(@time_roster) %> |
<%= link_to 'Back', time_rosters_path %>